include_defs('//bucklets/maven_jar.bucklet')

maven_jar(
  name = 'jcl-over-slf4j',
  id = 'org.slf4j:jcl-over-slf4j:1.7.7',
  sha1 = '56003dcd0a31deea6391b9e2ef2f2dc90b205a92',
  license = 'slf4j',
)
